name: Windows (Cygwin)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr {0}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: automake make cmake gcc-g++

      - name: Setup gitmodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=Release -UOPENCL_SDK_BUILD_SAMPLES

      - name: Build
        run: cmake --build ${{github.workspace}}\build

      - name: Run Example
        working-directory: ${{github.workspace}}\build\taskbench
        run: taskbench
